
#ifndef TRANSACTIONS_BINARY_TREE_TRANSACTION_H
#define TRANSACTIONS_BINARY_TREE_TRANSACTION_H

#include "types.h"

int TRANSACTION_generateId(Node* root);


#endif //TRANSACTIONS_BINARY_TREE_TRANSACTION_H
